on: 
  push:
  schedule:
  - cron: "0 0 * * *"

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: tinyply
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:ddiakopoulos/tinyply.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:${{ secrets.USER }}/tinyply.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: pytorch
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:pytorch/pytorch.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:${{ secrets.USER }}/pytorch.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: gaussian-splatting
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:graphdeco-inria/gaussian-splatting.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:${{ secrets.USER }}/gaussian-splatting.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: gaussian-splatting-cuda
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:MrNeRF/gaussian-splatting-cuda.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:${{ secrets.USER }}/gaussian-splatting-cuda.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: tiny-cuda-nn
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:NVlabs/tiny-cuda-nn.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:${{ secrets.USER }}/tiny-cuda-nn.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: sibr-core
        uses: wei/git-sync@v3
        with:
          source_repo: "https://gitlab.inria.fr/sibr/sibr_core.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:${{ secrets.USER }}/SIBR-Core.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: oneMKL
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:oneapi-src/oneMKL.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:${{ secrets.USER }}/oneMKL.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: oneTBB
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:oneapi-src/oneMKL.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:${{ secrets.USER }}/oneTBB.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: TensorRT
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:NVIDIA/TensorRT.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:${{ secrets.USER }}/TensorRT.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: colmap
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:colmap/colmap.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:${{ secrets.USER }}/colmap.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: opencv
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:opencv/opencv.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:${{ secrets.USER }}/opencv.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: opencv_contrib
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:opencv/opencv_contrib.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:${{ secrets.USER }}/opencv_contrib.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
