on: 
  push:
  schedule:
  - cron: "0 0 * * *"

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - name: tinyply
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:ddiakopoulos/tinyply.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:${{ secrets.USER }}/tinyply.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: pytorch
        uses: wei/git-sync@v3
        with:
          source_repo: "git@github.com:pytorch/pytorch.git"
          source_branch: "refs/remotes/source/*"
          destination_repo: "git@github.com:${{ secrets.USER }}/pytorch.git"
          destination_branch: "refs/heads/*"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
