on: 
  push:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  git-sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          
      - name: FastFlow
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://gitlab.inria.fr/landscapes/fastflow.git"
          destination_repo: "git@github.com:${{ secrets.USER }}/FastFlow.git"
          source_branch: "*"
          destination_branch: "*"
          sync_tags: "true"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          github_token: ${{ secrets.PAT }}
  
      - name: eigen
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://gitlab.com/libeigen/eigen.git"
          destination_repo: "git@github.com:${{ secrets.USER }}/eigen.git"
          source_branch: "*"
          destination_branch: "*"
          sync_tags: "true"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          github_token: ${{ secrets.PAT }}

      - name: sibr-core
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://gitlab.inria.fr/sibr/sibr_core.git"
          destination_repo: "git@github.com:${{ secrets.USER }}/SIBR-Core.git"
          source_branch: "*"
          destination_branch: "*"
          sync_tags: "true"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          github_token: ${{ secrets.PAT }}

      - name: mfs-chol
        uses: repo-sync/github-sync@v2
        with:
          source_repo: "https://gitlab.inria.fr/geomerix/public/mfs-chol.git"
          destination_repo: "git@github.com:${{ secrets.USER }}/mfs-chol.git"
          source_branch: "*"
          destination_branch: "*"
          sync_tags: "true"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          github_token: ${{ secrets.PAT }}
